[package]
name = "rust-web"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.21.2", features = ["full"] }
warp = { version = "0.3.3", features = ["websocket"] }
tokio-stream = "0.1.11"
futures-util = "0.3.24"
